/**
 * @file   om_fixed_parms.cpp
 * Definitions for fixed parameters for model 'Dynamis-Pop-3-06-ABC' - Generated by openM++ compiler
 *  
 *  Model version = 1.0.1.0
 *  Model created = 2021-03-17 14:19:34.883
 *  Model digest = 6eccce191106d267b262a54392186270
 */

#include "omc/cumrate.h"
#include "om_types1.h"

const double QNAN_F = std::numeric_limits<float>::quiet_NaN();
const double QNAN_D = std::numeric_limits<double>::quiet_NaN();
const double QNAN_LD = std::numeric_limits<long double>::quiet_NaN();

// model parameters (fixed)
