/**
 * @file   om_types0.h
 * Fundamental types for model 'Dynamis-Pop-3-06-ABC' - Generated by openM++ compiler
 *  
 *  Model version = 1.0.1.0
 *  Model created = 2021-03-17 14:19:34.883
 *  Model digest = 6eccce191106d267b262a54392186270
 */

#pragma once
#include <cmath>
#include "omc/fixed_precision.h"

// fundamental types
typedef signed char schar;
typedef long long llong;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef unsigned long long ullong;
typedef long double ldouble;
typedef fixed_precision<double> Time;
typedef double Time_t; // For use in model code
typedef fixed_precision<double> TIME;
typedef double TIME_t; // For use in model code
extern const Time_t time_infinite;
extern const Time_t TIME_INFINITE; // For Modgen source compatibility
extern const Time_t time_undef;
extern const Time_t TIME_UNDEF; // For Modgen source compatibility
typedef double real;
#define REAL_MAX DBL_MAX
typedef int integer;
typedef int counter;
typedef unsigned long long big_counter;

